### ISSUE TITLE
slog 2.4.1

### ISSUE THREAD

**Issue by crusty-dave** [slog-rs/slog#192]
Code that was working in 2.3.3 is no longer compiling in 2.4.1.

The following:

```
#[macro_export]
macro_rules! jerror (
    (#$tag:expr, $($args:tt)+) => {
        slog_log!($crate::jlog::GJLOG.logger, $crate::slog::Level::Error, $tag, $($args)+)
    };
    ($($args:tt)+) => {
        slog_log!($crate::jlog::GJLOG.logger, $crate::slog::Level::Error, "", $($args)+)
    };
);

```

Is yielding the following error now:

```
error: cannot find macro `__slog_builtin!` in this scope
   --> src\jdb\dummy\gin.rs:101:13
    |
101 |             jerror!("Error formatting file: {}", e);
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ in this macro invocation
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

```

This is a co-worker's library, I ran into the issue first when installing on Linux (Ubuntu 16 LTS), but after deleting Cargo.lock it is failing everywhere.  If I put 2.3.3 in my Cargo.toml it seems to still pick up 2.4.1, so I am guessing that something else has an explicit dependency on 2.4.1?

Note that he was apparently developing on nightly, and I on stable.  However, the prior version didn't seem to have an issue.

Anyway, currently stuck, could use some help figuring out why it broke with the latest...

c:\Users\dweaver\git\cic.c\srv\jaims\jaimslib>cargo -V
cargo 1.29.0 (524a578d7 2018-08-05)

c:\Users\dweaver\git\cic.c\srv\jaims\jaimslib>rustc -V
rustc 1.29.1 (b801ae664 2018-09-20)

I manually applied the versions from the last Cargo.lock that built (he was using "*", but still no joy, it always seems to choose slog 2.4.1 instead of 2.3.3.

```
[dependencies]
redis = "0.9.0"
json = "0.11.13"
lazy_static = "1.1.0"
config = "0.9.0"
slog = "2.3.3"
slog-atomic = "2.0.0"
sloggers = "0.2.8"
slog-async = "2.3.0"
slog-stdlog = "3"
#slog-scope-stdlog = "*"
slog-envlogger = "2.1.0"
env_logger = "0.3.5"
slog-term = "2.4.0"
slog-scope = "4.0.1"
chrono = "0.4.6"
failure = "0.1.2"
strfmt = "0.1.6"
common = {path = "../common"}
r2d2 = "0.8.2"
r2d2_redis = "0.8.0"
#r2d2_redis_cluster = "0.1.0"
#mongodb = "*"
#mongo_driver = "*"
#r2d2-mongodb = "*"
cached = "0.6.0"
strum = "0.10.0"
strum_macros = "0.10.0"
rand = "0.5.5"
uuid = { version = "0.7.0", features = ["v4"] }

```

**Comment by ubnt-intrepid** [comment]
The macro `slog_log!()` is use the inner macro `__slog_builtin!()` introduced for avoid problems around 2018-style macro imports. It you use specify macros to be imported within `#[macro_use(...)]` attribute, please add `__slog_builtin` to the list.

See also [the note in CHANGELOG.md](https://github.com/slog-rs/slog/blob/master/CHANGELOG.md#240---2018-09-19).

**Comment by crusty-dave** [comment]
Thank @ubnt-intrepid!  I originally tried to do this, I think the issue was the Crates.lock for the component still had slog 2.3.3 instead of 2.4.1, so trying to add the inner macro would fail.  Once all of the Cargo.lock files were deleted, I was able to add the __slog_builti to the list.

**Comment by dpc** [comment]
I'm closing due to lack of activity. Please re-open if still needed.
