### ISSUE TITLE
Failed compile after upgrade to 2.3.1

### ISSUE THREAD

**Issue by sbant** [slog-rs/slog#176]
I got lots of compile error after upgrade from 2.2.3 to 2.3.1

```
error[E0433]: failed to resolve. Could not find `module_path` in `$crate`
   --> src/main.rs:137:5
    |
137 |     info!("Program exited");
    |     ^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `module_path` in `$crate`
    |
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

looks like error in slog-scope crate, and maybe caused by 
"Export local inner macros"  commit 9a14db2d7bbcb7c28c37614d793427951a398dbd ?

**Comment by dpc** [comment]
Well, so much for trying to help 2018 edition preview. :)

Thanks for reporting. Stick with the previous version for now. I'll look into it when I get some time.

**Comment by pedrohjordao** [comment]
Subscribing to this issue. Had many errors similar to that one while trying to use 2018 edition. From the top of my had I remember `Could not find format_args in $crate`

**Comment by abonander** [comment]
I had breakage due to this commit in 2.3.0: https://github.com/slog-rs/slog/commit/b7d73fcabbfe89b8532ac631ea5b49c8867ca40a

Taking ownership where it was previously borrowing without changing how it's invoked is a breaking change which should *not* occur in a stable minor version (`x.y.0 where x > 0`) release.
